/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalManagement.AdministrativeWorkArea;


import userInterface.SystemAdminWorkArea.*;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.HospitalManagementMainJFrame;
/**
 *
 * @author Shreya
 */
public class AdminstrativeAccountManagement extends javax.swing.JPanel {

    /**
     * Creates new form MedTechnicalAccountsPage
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    CustomerDirectory customerDirectory;
    RestaurantDirectory restaurantDirectory;
    UserAccount userAccount;
    Restaurant restaurant;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public AdminstrativeAccountManagement(JPanel userProcessContainer , EcoSystem ecosystem) {
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        initComponents();
        if(ecosystem.getRestaurantDirectory() == null)
           ecosystem.setRestaurantDirectory(new RestaurantDirectory());
//        this.ecosystem = dB4OUtil.retrieveSystem();
        addrecordstotable(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        jTextFieldPatientID = new javax.swing.JTextField();
        jLabelPatientID = new javax.swing.JLabel();
        jLabelPatientName = new javax.swing.JLabel();
        jTextFieldPatientName = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAccounts = new javax.swing.JTable();
        jTextFieldPhoneNum = new javax.swing.JTextField();
        jLabelPhoneNum = new javax.swing.JLabel();
        jLabelInsuaranceNum = new javax.swing.JLabel();
        jTextFieldInsuranceNum = new javax.swing.JTextField();
        jTextFieldConsultationFee = new javax.swing.JTextField();
        jLabelConsultationFee = new javax.swing.JLabel();
        jLabelTestFee = new javax.swing.JLabel();
        jTextFieldTestFee = new javax.swing.JTextField();
        jTextFieldAdmissionFee = new javax.swing.JTextField();
        jLabelAdmissionFee = new javax.swing.JLabel();
        jLabelAmbulanceFee = new javax.swing.JLabel();
        jTextFieldAmbulanceFee = new javax.swing.JTextField();
        jTextFielddDiscount = new javax.swing.JTextField();
        jLabelDiscount = new javax.swing.JLabel();
        jLabelAdvancePaid = new javax.swing.JLabel();
        jTextFieldAdvancePaid = new javax.swing.JTextField();
        jTextFieldAmountDue = new javax.swing.JTextField();
        jLabelAmountDue = new javax.swing.JLabel();
        jLabelPharmacyBill = new javax.swing.JLabel();
        jTextFieldPharmacyBill = new javax.swing.JTextField();
        jTextFieldICUServices = new javax.swing.JTextField();
        jLabelICUServices = new javax.swing.JLabel();
        jLabelMedicalEquipment = new javax.swing.JLabel();
        jTextFieldMedicalEquipment = new javax.swing.JTextField();
        jTextFieldRoomRentServices = new javax.swing.JTextField();
        jLabelRoomRentServices = new javax.swing.JLabel();
        jLabelNursingCharges = new javax.swing.JLabel();
        jTextFieldNursingCharges = new javax.swing.JTextField();
        jTextFieldEmpID8 = new javax.swing.JTextField();
        jLabelTAX = new javax.swing.JLabel();
        jLabelGrandTotal = new javax.swing.JLabel();
        jTextFieldGrandTotal = new javax.swing.JTextField();
        jLabelSubTitle = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jButtonAddtoCart = new javax.swing.JButton();
        jButtonCheckout = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 70, 169));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1181, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 70, 169));
        jPanel1.setPreferredSize(new java.awt.Dimension(1381, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1245, 0, 0, 89));

        jLabelTitle.setBackground(new java.awt.Color(0, 70, 169));
        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("ACCOUNTS MANAGEMENT");
        add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 891, -1));

        jButtonHome.setBackground(new java.awt.Color(0, 70, 169));
        jButtonHome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 50, -1, -1));

        jTextFieldPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPatientIDActionPerformed(evt);
            }
        });
        add(jTextFieldPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 200, 150, -1));

        jLabelPatientID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPatientID.setText("Patient ID :");
        add(jLabelPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 104, -1));

        jLabelPatientName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPatientName.setText("Patient Name:");
        add(jLabelPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));
        add(jTextFieldPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 238, 150, -1));

        jButtonDelete.setText("DELETE");
        add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 750, -1, -1));

        jButtonCreate.setText("CREATE");
        add(jButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 750, -1, -1));

        jButtonUpdate.setText("UPDATE");
        add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 750, -1, -1));

        jButtonView.setText("VIEW");
        add(jButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 750, 70, 20));

        jTableAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Consulation Fee", "$60"},
                {"2", "Test Fee", "$50"},
                {"3", "Admission Fee", "$400"},
                {"4", "Ambulance Fee", "$200"},
                {"5", "Pharmacy Bill", "$80"},
                {"6", "ICU Services", "$1500"},
                {"7", "Medical Equipment", "$250"},
                {"8", "Room Rent ", "$300"},
                {"9", "Nursing Charges", "$100"},
                {"10", "Surgery Cost", "$3000"}
            },
            new String [] {
                "S.no", "Fee Particulars", "Cost"
            }
        ));
        jScrollPane1.setViewportView(jTableAccounts);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 830, 900, 180));

        jTextFieldPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNumActionPerformed(evt);
            }
        });
        add(jTextFieldPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 150, 20));

        jLabelPhoneNum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPhoneNum.setText("Phone Number :");
        add(jLabelPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 104, 10));

        jLabelInsuaranceNum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInsuaranceNum.setText("Insurance Number :");
        add(jLabelInsuaranceNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, 10));
        add(jTextFieldInsuranceNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 150, 20));

        jTextFieldConsultationFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConsultationFeeActionPerformed(evt);
            }
        });
        add(jTextFieldConsultationFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 150, -1));

        jLabelConsultationFee.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConsultationFee.setText("Consultation Fee : ");
        add(jLabelConsultationFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 104, -1));

        jLabelTestFee.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTestFee.setText("Test Fee :");
        add(jLabelTestFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));
        add(jTextFieldTestFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 150, -1));

        jTextFieldAdmissionFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdmissionFeeActionPerformed(evt);
            }
        });
        add(jTextFieldAdmissionFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 150, -1));

        jLabelAdmissionFee.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdmissionFee.setText("Admission Charges :");
        add(jLabelAdmissionFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 104, -1));

        jLabelAmbulanceFee.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAmbulanceFee.setText("Ambulance Fee :");
        add(jLabelAmbulanceFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, -1, -1));
        add(jTextFieldAmbulanceFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 150, -1));

        jTextFielddDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddDiscountActionPerformed(evt);
            }
        });
        add(jTextFielddDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 790, 150, -1));

        jLabelDiscount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDiscount.setText("Discount Applied :");
        add(jLabelDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 790, 104, -1));

        jLabelAdvancePaid.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdvancePaid.setText("Advance Paid :");
        add(jLabelAdvancePaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, -1, -1));
        add(jTextFieldAdvancePaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 150, -1));

        jTextFieldAmountDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmountDueActionPerformed(evt);
            }
        });
        add(jTextFieldAmountDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, 150, -1));

        jLabelAmountDue.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAmountDue.setText("Amount Due :");
        add(jLabelAmountDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 104, -1));

        jLabelPharmacyBill.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPharmacyBill.setText("Pharmacy Bill :");
        add(jLabelPharmacyBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));
        add(jTextFieldPharmacyBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 150, -1));

        jTextFieldICUServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldICUServicesActionPerformed(evt);
            }
        });
        add(jTextFieldICUServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 150, -1));

        jLabelICUServices.setForeground(new java.awt.Color(255, 255, 255));
        jLabelICUServices.setText("ICU Services :");
        add(jLabelICUServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 104, -1));

        jLabelMedicalEquipment.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMedicalEquipment.setText("Medical Equipment :");
        add(jLabelMedicalEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, -1, -1));
        add(jTextFieldMedicalEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 150, -1));

        jTextFieldRoomRentServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRoomRentServicesActionPerformed(evt);
            }
        });
        add(jTextFieldRoomRentServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 150, -1));

        jLabelRoomRentServices.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRoomRentServices.setText("Room Rent Service :");
        add(jLabelRoomRentServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 660, 104, -1));

        jLabelNursingCharges.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNursingCharges.setText("Nursing Charges :");
        add(jLabelNursingCharges, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 700, -1, -1));
        add(jTextFieldNursingCharges, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, 150, -1));

        jTextFieldEmpID8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpID8ActionPerformed(evt);
            }
        });
        add(jTextFieldEmpID8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 750, 150, -1));

        jLabelTAX.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTAX.setText("TAX :");
        add(jLabelTAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 750, 104, -1));

        jLabelGrandTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGrandTotal.setText("Grand Total :");
        add(jLabelGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, -1, -1));
        add(jTextFieldGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, 150, -1));

        jLabelSubTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubTitle.setText("FEE PARTICULARS");
        add(jLabelSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 250, 20));

        jButtonSearch.setText("SEARCH");
        add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, -1, -1));

        jButtonAddtoCart.setText("Add to Cart");
        add(jButtonAddtoCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1040, -1, -1));

        jButtonCheckout.setText("Checkout");
        jButtonCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckoutActionPerformed(evt);
            }
        });
        add(jButtonCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 1040, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.show(userProcessContainer,"Sysadmin");
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jTextFieldPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPatientIDActionPerformed

    private void jTextFieldPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNumActionPerformed

    private void jTextFieldConsultationFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConsultationFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConsultationFeeActionPerformed

    private void jTextFieldAdmissionFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdmissionFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdmissionFeeActionPerformed

    private void jTextFielddDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddDiscountActionPerformed

    private void jTextFieldAmountDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmountDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmountDueActionPerformed

    private void jTextFieldICUServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldICUServicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldICUServicesActionPerformed

    private void jTextFieldRoomRentServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRoomRentServicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRoomRentServicesActionPerformed

    private void jTextFieldEmpID8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpID8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpID8ActionPerformed

    private void jButtonCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCheckoutActionPerformed
    private void clearFields(){
        restaurantID.setText("");
        restaurantName.setText("");
        restaurantPincode.setText("");
        restaurantPhone.setText("");
        restaurantPassword.setText("");
    }
    public ArrayList<String> check_empty_field(){
        ArrayList<String> user_input = new ArrayList<>();
        String user_rest_id = restaurantID.getText();
        String user_rest_name = restaurantName.getText();
        String user_pincode = restaurantPincode.getText();
        String user_contact_no = restaurantPhone.getText();
        String user_password = restaurantPassword.getText();
        
        
        if(user_rest_id.isEmpty()){
            JOptionPane.showMessageDialog(this, "Restaurant ID can't be left empty.");
        }
        else if(user_rest_name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Restaurant Name can't be left empty.");
        }
        else if(user_pincode.isEmpty()){
            JOptionPane.showMessageDialog(this, "Restaurant Pincode can't be left empty.");
        }
        else if(user_contact_no.isEmpty()){
            JOptionPane.showMessageDialog(this, "Restaurant Contact No can't be left empty.");
        }
        else if(user_password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a Password.");
        }
        
        
        user_input.add(user_rest_id);
        user_input.add(user_rest_name);
        user_input.add(user_pincode);
        user_input.add(user_contact_no);
        user_input.add(user_password);
        
        return user_input;
        
    }
    private Restaurant set_user_input_values(Restaurant restaurant, ArrayList<String> user_input){
        
        restaurant.setRest_id(user_input.get(0));
        restaurant.setName(user_input.get(1));
        restaurant.setRest_pincode(user_input.get(2));
        restaurant.setContact_no(user_input.get(3));
        return restaurant;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddtoCart;
    private javax.swing.JButton jButtonCheckout;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabelAdmissionFee;
    private javax.swing.JLabel jLabelAdvancePaid;
    private javax.swing.JLabel jLabelAmbulanceFee;
    private javax.swing.JLabel jLabelAmountDue;
    private javax.swing.JLabel jLabelConsultationFee;
    private javax.swing.JLabel jLabelDiscount;
    private javax.swing.JLabel jLabelGrandTotal;
    private javax.swing.JLabel jLabelICUServices;
    private javax.swing.JLabel jLabelInsuaranceNum;
    private javax.swing.JLabel jLabelMedicalEquipment;
    private javax.swing.JLabel jLabelNursingCharges;
    private javax.swing.JLabel jLabelPatientID;
    private javax.swing.JLabel jLabelPatientName;
    private javax.swing.JLabel jLabelPharmacyBill;
    private javax.swing.JLabel jLabelPhoneNum;
    private javax.swing.JLabel jLabelRoomRentServices;
    private javax.swing.JLabel jLabelSubTitle;
    private javax.swing.JLabel jLabelTAX;
    private javax.swing.JLabel jLabelTestFee;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAccounts;
    private javax.swing.JTextField jTextFieldAdmissionFee;
    private javax.swing.JTextField jTextFieldAdvancePaid;
    private javax.swing.JTextField jTextFieldAmbulanceFee;
    private javax.swing.JTextField jTextFieldAmountDue;
    private javax.swing.JTextField jTextFieldConsultationFee;
    private javax.swing.JTextField jTextFieldEmpID8;
    private javax.swing.JTextField jTextFieldGrandTotal;
    private javax.swing.JTextField jTextFieldICUServices;
    private javax.swing.JTextField jTextFieldInsuranceNum;
    private javax.swing.JTextField jTextFieldMedicalEquipment;
    private javax.swing.JTextField jTextFieldNursingCharges;
    private javax.swing.JTextField jTextFieldPatientID;
    private javax.swing.JTextField jTextFieldPatientName;
    private javax.swing.JTextField jTextFieldPharmacyBill;
    private javax.swing.JTextField jTextFieldPhoneNum;
    private javax.swing.JTextField jTextFieldRoomRentServices;
    private javax.swing.JTextField jTextFieldTestFee;
    private javax.swing.JTextField jTextFielddDiscount;
    // End of variables declaration//GEN-END:variables

    private void addrecordstotable(int par) {
        restaurantDirectory = ecosystem.getRestaurantDirectory();
        DefaultTableModel model = (DefaultTableModel) RestaurantsTable.getModel();
//        DefaultComboBo/xModel dc = new DefaultComboBoxModel();
        model.setRowCount(0);
        ArrayList<Restaurant> restaurants = restaurantDirectory.getRestaurantList();
        for(Restaurant r: restaurants)
        {
            model.addRow(new Object[]{r,r.getName(),r.getContact_no(),r.getRest_pincode(),r.getUserAccount().getPassword()});
        }
        RestaurantsTable.setModel(model);
        dB4OUtil.storeSystem(ecosystem);
    }
}
