/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalManagement.HospitalAdminWorkArea;


import HospitalManagement.Hospital.Hospital;
import MainCentralisationSystem.MedicalServiceCentralisationEcoSystem;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MyPC1
 */
public class HospitalAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    MedicalServiceCentralisationEcoSystem hospitalManagementEcoSystem;
    Hospital hospital;
    public HospitalAdminWorkAreaJPanel(JPanel userProcessContainer,MedicalServiceCentralisationEcoSystem hospitalManagementEcoSystem, Hospital hospital) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.hospitalManagementEcoSystem = hospitalManagementEcoSystem;
        this.hospital = hospital;
        jPanel1.setVisible(false);
        //jSplitPane.setVisible(false);
        //jPanel2.setVisible(true);
        populateTree();
    }
    
    public void populateTree(){
        //DefaultTreeModel model=(DefaultTreeModel)Admin.getModel();
       // Add the code for draw your system structure shown by JTree
       
      //  model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonMedTechnicalAccountsPage = new javax.swing.JButton();
        jButtonAdministrativeAccountsPage = new javax.swing.JButton();
        jButtonOperationalAccountsPage = new javax.swing.JButton();
        btnManageAdmin2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1720, 1080));
        setLayout(new java.awt.BorderLayout());

        jSplitPane.setPreferredSize(new java.awt.Dimension(1720, 1080));

        jPanel2.setBackground(new java.awt.Color(0, 70, 169));
        jPanel2.setPreferredSize(new java.awt.Dimension(1720, 1080));

        jButtonMedTechnicalAccountsPage.setBackground(new java.awt.Color(0, 70, 169));
        jButtonMedTechnicalAccountsPage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonMedTechnicalAccountsPage.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMedTechnicalAccountsPage.setText("Technical & Lab Testing Team");
        jButtonMedTechnicalAccountsPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedTechnicalAccountsPageActionPerformed(evt);
            }
        });

        jButtonAdministrativeAccountsPage.setBackground(new java.awt.Color(0, 70, 169));
        jButtonAdministrativeAccountsPage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonAdministrativeAccountsPage.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdministrativeAccountsPage.setText("Admin & Accounting Team");
        jButtonAdministrativeAccountsPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrativeAccountsPageActionPerformed(evt);
            }
        });

        jButtonOperationalAccountsPage.setBackground(new java.awt.Color(0, 70, 169));
        jButtonOperationalAccountsPage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonOperationalAccountsPage.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOperationalAccountsPage.setText("Operational Team");
        jButtonOperationalAccountsPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperationalAccountsPageActionPerformed(evt);
            }
        });

        btnManageAdmin2.setBackground(new java.awt.Color(0, 70, 169));
        btnManageAdmin2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnManageAdmin2.setForeground(new java.awt.Color(255, 255, 255));
        btnManageAdmin2.setText("Search Employee");
        btnManageAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdmin2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonOperationalAccountsPage, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(jButtonAdministrativeAccountsPage, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(jButtonMedTechnicalAccountsPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageAdmin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(941, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jButtonAdministrativeAccountsPage)
                .addGap(67, 67, 67)
                .addComponent(jButtonOperationalAccountsPage)
                .addGap(61, 61, 61)
                .addComponent(jButtonMedTechnicalAccountsPage)
                .addGap(58, 58, 58)
                .addComponent(btnManageAdmin2)
                .addContainerGap(530, Short.MAX_VALUE))
        );

        jSplitPane.setRightComponent(jPanel2);

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 1080));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1078, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanel1);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMedTechnicalAccountsPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedTechnicalAccountsPageActionPerformed
        // TODO add your handling code here:
        MedTechnicalAccountsPage medTechnicalAccountsPage = new MedTechnicalAccountsPage(userProcessContainer,hospitalManagementEcoSystem, hospital);
        userProcessContainer.add("MedTechnicalAccountsPage",medTechnicalAccountsPage);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"MedTechnicalAccountsPage");
    }//GEN-LAST:event_jButtonMedTechnicalAccountsPageActionPerformed

    private void jButtonAdministrativeAccountsPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrativeAccountsPageActionPerformed
        
        AdministrativeAccountsPage administrativeAccountsPage = new AdministrativeAccountsPage(userProcessContainer,hospitalManagementEcoSystem, hospital);
        userProcessContainer.add("AdministrativeAccountsPage",administrativeAccountsPage);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"AdministrativeAccountsPage");
    }//GEN-LAST:event_jButtonAdministrativeAccountsPageActionPerformed

    private void jButtonOperationalAccountsPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperationalAccountsPageActionPerformed
        OperationalAccountsPage operationalAccountsPage = new OperationalAccountsPage(userProcessContainer,hospitalManagementEcoSystem, hospital);
        userProcessContainer.add("OperationalAccountsPage",operationalAccountsPage);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"OperationalAccountsPage");
    }//GEN-LAST:event_jButtonOperationalAccountsPageActionPerformed

    private void btnManageAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdmin2ActionPerformed
        //       ManageDeliveryManWorkArena manageDeliveryManWorkArena = new ManageDeliveryManWorkArena(userProcessContainer,hospitalManagementEcoSystem);
        //        userProcessContainer.add("manageDeliveryManWorkArena",manageDeliveryManWorkArena);
        //        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        //        cardLayout.show(userProcessContainer,"manageDeliveryManWorkArena");
    }//GEN-LAST:event_btnManageAdmin2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAdmin2;
    private javax.swing.JButton jButtonAdministrativeAccountsPage;
    private javax.swing.JButton jButtonMedTechnicalAccountsPage;
    private javax.swing.JButton jButtonOperationalAccountsPage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
