/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalManagement.MedTechnicalWorkArea;

import HospitalManagement.Hospital.Hospital;
import userInterface.SystemAdminWorkArea.*;
import MainCentralisationSystem.MedicalServiceCentralisationEcoSystem;
import MainCentralisationSystem.HospitalManagementEnterprise;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
//import userinterface.createNewUser.createLogin;

public class MedTechnicalWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    MedicalServiceCentralisationEcoSystem medicalServiceCentralisationEcoSystem;
    Hospital hospital;
    public MedTechnicalWorkAreaJPanel(JPanel userProcessContainer,MedicalServiceCentralisationEcoSystem medicalServiceCentralisationEcoSystem, Hospital hospital) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.medicalServiceCentralisationEcoSystem = medicalServiceCentralisationEcoSystem;
        this.hospital = hospital;
        jPanel1.setVisible(false);
        //jSplitPane.setVisible(false);
        //jPanel2.setVisible(true);
//        populateTree();
    }
    
    public void populateTree(){
        //DefaultTreeModel model=(DefaultTreeModel)Admin.getModel();
       // Add the code for draw your system structure shown by JTree
       
      //  model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonTestDatabase = new javax.swing.JButton();
        jButtonEmployeeAttendance = new javax.swing.JButton();
        jButtonPatientTest = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1720, 1080));
        setLayout(new java.awt.BorderLayout());

        jSplitPane.setPreferredSize(new java.awt.Dimension(1720, 1080));

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 1080));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 70, 169));
        jPanel2.setPreferredSize(new java.awt.Dimension(1720, 1080));

        jButtonTestDatabase.setBackground(new java.awt.Color(0, 70, 169));
        jButtonTestDatabase.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonTestDatabase.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTestDatabase.setText("Test Database");
        jButtonTestDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestDatabaseActionPerformed(evt);
            }
        });

        jButtonEmployeeAttendance.setBackground(new java.awt.Color(0, 70, 169));
        jButtonEmployeeAttendance.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonEmployeeAttendance.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmployeeAttendance.setText("Employee Attendance");
        jButtonEmployeeAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeAttendanceActionPerformed(evt);
            }
        });

        jButtonPatientTest.setBackground(new java.awt.Color(0, 70, 169));
        jButtonPatientTest.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonPatientTest.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPatientTest.setText("Patient Test");
        jButtonPatientTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPatientTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTestDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEmployeeAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(jButtonPatientTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1005, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jButtonTestDatabase)
                .addGap(50, 50, 50)
                .addComponent(jButtonEmployeeAttendance)
                .addGap(53, 53, 53)
                .addComponent(jButtonPatientTest)
                .addContainerGap(606, Short.MAX_VALUE))
        );

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmployeeAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeAttendanceActionPerformed
//        MedTechnicalEmployeeAttendance medTechnicalEmployeeAttendance = new MedTechnicalEmployeeAttendance(userProcessContainer,medicalServiceCentralisationEcoSystem);
//        userProcessContainer.add("medTechnicalEmployeeAttendance",medTechnicalEmployeeAttendance);
//        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
//        cardLayout.show(userProcessContainer,"medTechnicalEmployeeAttendance");
    }//GEN-LAST:event_jButtonEmployeeAttendanceActionPerformed

    private void jButtonTestDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestDatabaseActionPerformed

        MedTechnicalTestDatabase medTechnicalTestDatabase = new MedTechnicalTestDatabase(userProcessContainer,medicalServiceCentralisationEcoSystem, hospital);
        userProcessContainer.add("medTechnicalTestDatabase",medTechnicalTestDatabase);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"medTechnicalTestDatabase");
    }//GEN-LAST:event_jButtonTestDatabaseActionPerformed

    private void jButtonPatientTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPatientTestActionPerformed
        // TODO add your handling code here:
        MedTechnicalPatientTest medTechnicalPatientTest = new MedTechnicalPatientTest(userProcessContainer,medicalServiceCentralisationEcoSystem, hospital);
        userProcessContainer.add("medTechnicalPatientTest",medTechnicalPatientTest);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"medTechnicalPatientTest");
    }//GEN-LAST:event_jButtonPatientTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEmployeeAttendance;
    private javax.swing.JButton jButtonPatientTest;
    private javax.swing.JButton jButtonTestDatabase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
